### ISSUE TITLE
Instructions in readme

### ISSUE THREAD

**Issue by kvsm** [CallumD/Electune#1]
In the readme,

`git clone https://github.com/kvsm/electune_spotify_client ~/Spotify`

should read;

`git clone https://github.com/kvsm/electune_spotify_client ~/Spotify/electune`

as the project name is different from the identifer in the manifest (and specifying the Spotify directory on its own will unpack the project there, and not a in subdir).

**Comment by CallumD** [comment]
This issue has been fixed under commit 9259327 please review and if your happy with the changes close this issue. Thanks!

**Comment by kvsm** [comment]
Sorted. :)
